environments:
  #prod:
  default:
    values:
      - ../../global-values.yaml

---

repositories:
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    chart: prometheus-community/prometheus
    version: 27.5.1
    namespace: {{ .Values.monitoring.namespace }}
    # values:
    #   - ./prometheus/values.yaml
