environments:
  #prod:
  default:
    values:
      - ../../global-values.yaml

---

repositories:
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    chart: prometheus
    version: prometheus-25.9.0
    namespace: {{ .Values.monitoring.namespace }}
    # values:
    #   - ./prometheus/values.yaml
