environments:
  #prod:
  default:
    values:
      - ../prod/global-values.yaml

---

repositories:
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    chart: prometheus
    version: 25.9.0
    namespace: {{ .Values.argocd.namespace }}
    values:
      - ./prometheus/values.yaml
