apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: media-apps
  project: default
  source:
    repoURL: https://gitlab.irdeto.com/itv/itv-pnp-k8s-apps.git
    targetRevision: main
    path: media-apps/sonarr
    plugin:
      env:
        - name: ENV_NAME
          value: prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

