environments:
  #prod:
  default:
    values:
      - ../../global-values.yaml

---
releases:
  - name: app-of-apps
    chart: ../../../base/argocd-apps
    namespace: {{ .Values.argocd.namespace }}
    values:
      - ./argocd-apps/values.yaml
 