environments:
  #prod:
  default:
    values:
      - ../../global-values.yaml

---
releases:
  - name:  {{ .Values.media.namespace }}
    chart: ../../../base/namespace
    namespace: {{ .Values.media.namespace }}

  - name: app-of-apps
    chart: ../../../base/argocd-apps
    namespace: {{ .Values.argocd.namespace }}
    values:
      - ./argocd-apps/values.yaml
 