environments:
  #prod:
  default:
    values:
      - ../../global-values.yaml
      - ../../../image-tags/*.yaml
 
---

repositories:
  - name: bjw-s
    url: https://bjw-s.github.io/helm-charts
  - name: common
    url: https://library-charts.k8s-at-home.com

releases:
  - name: sonarr
    chart: ../../../base/sonarr/sonarr
    namespace: {{ .Values.media.namespace }}
    values:
      - ./sonarr/sonarr/values.yaml
    set:
      - name: image.repository
        value: {{ .Values.sonarr.image.repository }}
      - name: image.tag
        value: {{ .Values.sonarr.image.tag }}

  - name: radarr
    chart: ../../../base/radarr/radarr
    namespace: {{ .Values.media.namespace }}
    values:
      - ./radarr/radarr/values.yaml
    set:
      - name: image.repository
        value: {{ .Values.radarr.image.repository }}
      - name: image.tag
        value: {{ .Values.radarr.image.tag }}

  - name: prowlarr
    namespace: media
    chart: ../../../base/prowlarr/prowlarr
    values:
      - ./prowlarr/prowlarr/values.yaml
    set:
      - name: image.repository
        value: {{ .Values.prowlarr.image.repository }}
      - name: image.tag
        value: {{ .Values.prowlarr.image.tag }}
  
  - name: transmission
    namespace: media
    chart: ../../../base/transmission/transmission
    values:
      - ./transmission/transmission/values.yaml
    set:
      - name: image.repository
        value: {{ .Values.transmission.image.repository }}
      - name: image.tag
        value: {{ .Values.transmission.image.tag }}