environments:
  prod:
    values:
      - ../../environments/prod/global-values.yaml

---
releases:
  - name: sonarr
    chart: ../../base/sonarr/sonarr
    namespace: {{ .Values.mediamanager.namespace }}
    values:
      - ./sonarr/values.yaml
 