environments:
  #prod:
  default:
    values:
      - ../../global-values.yaml
      - ../../../image-tags/*.yaml

---

releases:
  - name: config
    namespace: {{ .Values.media.namespace }}
    chart: ../../../base/nfs-mount/config
    # values:
    #   - ./media/nfs-mount/config/values.yaml

  - name: media
    namespace: {{ .Values.media.namespace }}
    chart: ../../../base/nfs-mount/media
    # values:
    #   - ./media/nfs-mount/config/values.yaml

  - name: transmission
    namespace: {{ .Values.media.namespace }}
    chart: ../../../base/nfs-mount/transmission
    # values:
    #   - ./media/nfs-mount/config/values.yaml