apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/dudilander/arr-stack-k8s-argo-apps.git
    targetRevision: main
    path: prod/cluster-components/argocd-apps
    plugin:
      name: helmfile
      env:
       - name: ARGOCD_APP_NAMESPACE
         value: "my-argocd-project"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

