apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-mount
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  project: default
  source:
    repoURL: https://github.com/dudilander/arr-stack-k8s-argo-apps.git
    targetRevision: main
    path: prod/cluster-components/utilities
    plugin:
      name: helmfile
  syncPolicy:
    autautomated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

