#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/onedr0p/bazarr
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: "Europe/Amsterdam"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    type: NodePort
    ports:
      http:
        port: 6767
        nodePort: 30067

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /config
    subPath: bazarr
    accessMode: ReadWriteOnce
    size: 100Gi
    existingClaim: config

  media:
    enabled: true
    mountPath: /media
    accessMode: ReadWriteOnce
    size: 100Gi
    existingClaim: media
