environments:
  prod:
    values:
      - ../../environments/prod/global-values.yaml

---
releases:
  - name: argocd
    chart: ../../base/argocd/argocd
    namespace: {{ .Values.mediamanager.namespace }}
    values:
      - ./argocd/values.yaml
 