environments:
  #prod:
  default:
    values:
      - ../prod/global-values.yaml

---

repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    chart: argo/argo-cd
    version: 7.8.10
    namespace: {{ .Values.argocd.namespace }}
    values:
      - ./argocd/values.yaml
