environments:
  #prod:
  default:
    values:
      - ../environments/prod/global-values.yaml

---
releases:
  - name: argocd
    chart: ../base/argocd/argocd
    namespace: {{ .Values.argocd.namespace }}
    values:
      - ./argocd/values.yaml
 