apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: media
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  project: default
  source:
    repoURL: https://github.com/dudilander/arr-stack-k8s-argo-apps.git
    targetRevision: main
    path: media/sonarr
    plugin:
      env:
        - name: ENV_NAME
          value: prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

